name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Static analysis
      run: |
        pycodestyle osm_painter ./example.py
        pylint --load-plugins pylint_quotes osm_painter ./example.py
        mypy osm_painter ./example.py
