name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-quotes mypy pycodestyle
    - name: Analysing the code with pylint
      run: |
        pycodestyle osm_painter
        pylint --load-plugins pylint_quotes osm_painter
        mypy osm_painter
